version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=database"
    ports:
      - "33060:3306"
  backend:
    build:
      context: backend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - database
    user: backend
  frontend:
    build:
      context: frontend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "4200:4200"
    user: frontend